### ISSUE TITLE
直方图很不错，可否支持stack属性，来实现堆叠直方图的效果呢？

### ISSUE THREAD

**Issue by candy4290** [ecomfe/echarts-stat#54]
直方图很不错，可否支持stack属性，来实现堆叠直方图的效果呢？
```[tasklist]
### Tasks
```

**Comment by echodis** [comment]
您好，这里是周敏。您的来信我已收到，我会在查看后的第一时间给你回复。

**Comment by candy4290** [comment]
目前方案：使用柱状图来实现。调整barWidth:100%;然后动态调整axisLabel的padding，进行偏移。非常好用，哈哈哈哈
