### ISSUE TITLE
echarts扩展是否有API和配置项说明？

### ISSUE THREAD

**Issue by gitXiaoQing** [ecomfe/echarts-stat#6]
echarts扩展是否有API文档说明？类似http://echarts.baidu.com/option.html
谢谢！

**Comment by Ovilia** [comment]
没有，可以参考现有的几个插件来写：
https://github.com/ecomfe/echarts-liquidfill
https://github.com/ecomfe/echarts-wordcloud

**Comment by gitXiaoQing** [comment]
好的，谢谢！

**Comment by gitXiaoQing** [comment]
@Ovilia ，您好，echarts统计扩展的聚类[demo](http://gallery.echartsjs.com/editor.html?c=xSkBOEaGtx&v=13)，修改里面的clusterNumber=1，后面的result = ecStat.clustering.hierarchicalKMeans..不会出来正常结果。请问这是正常现象还是clusterNumber就不能设置为1？

**Comment by Ovilia** [comment]
@deqingli 作者来解答吧~

**Comment by deqingli** [comment]
@gitXiaoQing 你好，不好意思，之前业务很忙，你说的问题，我今天看下，尽快给你答复

**Comment by deqingli** [comment]
@gitXiaoQing 您好，这个问题已经解决了，在层次聚类里面一开始是将整个数据集作为一个数据簇，然后再分割成两个，三个....直到 k 个。所以 k 必须大于 1

**Comment by gitXiaoQing** [comment]
谢谢！
