### ISSUE TITLE
【建议】单测 + 移除 define

### ISSUE THREAD

**Issue by hustcc** [ecomfe/echarts-stat#8]
-  这个模块是一个纯 js 数学统计和计算的模块，应该需要一个单测来保证代码的正确性。
 - 移除 define 定义文件模块的方式，通过打包，生成最终的 dist 支持 amd（这个也是因为在 jest 环境无法引入 amd 模块文件，无法进行测试）。

**Comment by deqingli** [comment]
单测是一直想加的，苦于没有时间，也欢迎大佬给我们提 PR

**Comment by hustcc** [comment]
见 pr #10.
